### PR TITLE
chore - rename files

### PR DESCRIPTION
**Pull request by qguyk**

### CODE REVIEW

**Comment by yomach** [comment]
I was wondering about it, we need to decide on the naming convention...
I was following the SDK: QuantumMachinesManger

**Comment by qguyk** [comment]
> I was wondering about it, we need to decide on the naming convention... I was following the SDK: QuantumMachinesManger

I think it's better if we follow pep-8
https://www.python.org/dev/peps/pep-0008/#package-and-module-names

**Comment by qguyk** [comment]
@yomach the test pass when i used a wrong table, can you please add a small test for the randomized_benchmark?

**Review by yomach — APPROVED** [review]
Please see my changes and approve :)

**Comment by qguyk** [comment]
@yomach look good, lets squash and merge?

**Pull request merged**
