### PR TITLE
Small fixes and live plotting

### PR DESCRIPTION
**Pull request by TheoLaudatQM**
Fix a small issue with raw adc traces and add a live-plotting option when averaging on the most outer loop

### CODE REVIEW

**Comment by TheoLaudatQM** [comment]
Now it also keep the qm_id in case close_other_machines is False and the user wants to update the qm
And there is a new method to update the readout length of a given element and operation

**Review by yomach — COMMENTED** [review]
Looks good, but are we testing this in any way?

**Comment by TheoLaudatQM** [comment]
I am testing yes, but do you mean with unitary tests?

**Comment by yomach** [comment]
Yes, I mean automated tests in the package.
It'll be good to add them, if possible...
If it's too complicated, then it's an open task

**Comment by TheoLaudatQM** [comment]
Yeah I always had it in the back of my mine, but I always had more pressing things to do and it requires a connection to an OPX our cloud simulator...

**Review by yomach — APPROVED** [review]

**Pull request merged**
